version: '3.8'

services:
  valkey:
    image: valkey/valkey:8.1.3
    container_name: valpop-valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    command: valkey-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Valkey CLI for debugging/management
  valkey-cli:
    image: valkey/valkey:8.1.3
    container_name: valpop-valkey-cli
    depends_on:
      - valkey
    command: valkey-cli -h valkey
    profiles:
      - cli
    stdin_open: true
    tty: true

  minio:
    image: minio/minio
    command: server /data --console-address ":10000"
    volumes:
      # These vars are defined in .env
      # These are configurable
      # Ensure the directories exist prior to running this file
      - minio_conf:/root/.minio:Z
      - minio_data:/data:Z
    ports:
      - '9000:9000'
      - '10000:10000'
    environment:
      - MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=$MINIO_SECRET_KEY

  minio-createbuckets:
    image: minio/mc
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY" || exit 1;
      /usr/bin/mc mb --ignore-existing minio/frontend;
      /usr/bin/mc anonymous set upload minio/frontend;
      "

volumes:
  valkey_data:
    driver: local

  minio_conf: {}
  minio_data: {}
