apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RedHatInsights/valpop?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
    pipelinesascode.tekton.dev/pipeline: https://github.com/RedHatInsights/konflux-pipelines/blob/main/pipelines/docker-build-run-unit-tests-dynamic-env.yaml
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: valpop
    appstudio.openshift.io/component: valpop
    pipelines.appstudio.openshift.io/type: build
  name: valpop-on-push
  namespace: hcc-platex-services-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/hcc-platex-services-tenant/valpop:{{revision}}
  - name: dockerfile
    value: /Dockerfile
  - name: unit-tests-script
    value: ./run-unit-tests.sh
  - name: PGSQL_USER
    value: ""
  - name: PGSQL_PASSWORD
    value: ""
  - name: PGSQL_HOSTNAME
    value: ""
  - name: PGSQL_PORT
    value: ""
  - name: PGSQL_DATABASE
    value: ""
  - name: UNLEASH_API_TOKEN
    value: ""
  - name: UNLEASH_ADMIN_TOKEN
    value: ""
  - name: env-vars
    value: |
      TEST_BUCKET=test-bucket
      TEST_NAMESPACE=test-populate
      MINIO_ENDPOINT=localhost:9000
      TEST_DIR=build
  pipelineRef:
    name: docker-build
  taskRunTemplate:
    serviceAccountName: build-pipeline-valpop
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
